sudo: required
services:
  - docker

before_install:
  - docker build -t aniketbiswas21/docker-prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true aniketbiswas21/docker-prod-workflow npm run test
