sudo: required
services:
  - docker

before_install:
  - docker build -t aniketbiswas21/docker-prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true aniketbiswas21/docker-prod-workflow npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-prod-workflow
  env: "DockerProdWorkflow-env"
  bucket_name: "elasticbeanstalk-us-east-2-460847558312"
  bucket_path: "docker-prod-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
